trigger:
  - master
pool:
  vmImage: "ubuntu-latest"
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "10.x"
    displayName: "Install Node.js"
  - script: |
      cd scripts
      npm install
      node publish.js
    displayName: "npm install, build, deploy"
